// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABI4wg7dJH05PxLYd8-uKqNNsntOF1Wcc',
    appId: '1:40958619055:web:b560ab57699db35653935a',
    messagingSenderId: '40958619055',
    projectId: 'intaketrackvirtualassistant',
    authDomain: 'intaketrackvirtualassistant.firebaseapp.com',
    storageBucket: 'intaketrackvirtualassistant.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2mxR1typmZU2mMSbODnuUYR2SsgVsLBo',
    appId: '1:40958619055:android:e28ca52f7a97159053935a',
    messagingSenderId: '40958619055',
    projectId: 'intaketrackvirtualassistant',
    storageBucket: 'intaketrackvirtualassistant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pEhsbmsNs46gfr6CMjDWyg40z4bfwCA',
    appId: '1:40958619055:ios:c7cbe3c6a97b9e6653935a',
    messagingSenderId: '40958619055',
    projectId: 'intaketrackvirtualassistant',
    storageBucket: 'intaketrackvirtualassistant.appspot.com',
    iosBundleId: 'com.ntu.chatgptBasedVirtualAssistantForDietAndNutrition',
  );
}
